<a href="https://colab.research.google.com/github/arewadataScience/ArewaDS-Deep-Learning/blob/main/Part_1_Deep_Learning_with_Pytorch/week1/week_1_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Arewa DataScience Academy
### Deep Learning Cohort 1.0

### WEEK 1 Exercises

### Exercises:
Please, see week 1 exercises from [**Learn PyTorch for Deep Learning**: 00. Pytorch Fundamentals](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

### Additional Exercise

## Arewa DataScience Academy
### Deep Learning Cohort 1.0

### WEEK 1 Exercises

### Exercises:
Please, see week 1 exercises from [**Learn PyTorch for Deep Learning**: 00. Pytorch Fundamentals](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

**1. Create a random tensor with shape (7, 7).**

In [ ]:
import torch

In [ ]:
randtorch = torch.rand(size=(7, 7))
randtorch, randtorch.shape

(tensor([[0.7671, 0.4912, 0.6005, 0.4937, 0.5376, 0.9072, 0.3686],
         [0.2372, 0.6986, 0.7255, 0.5894, 0.5360, 0.1594, 0.6024],
         [0.9616, 0.0315, 0.4830, 0.9373, 0.1805, 0.4876, 0.2305],
         [0.4420, 0.6227, 0.8761, 0.4851, 0.2178, 0.9586, 0.0512],
         [0.6204, 0.0304, 0.9886, 0.8675, 0.9989, 0.7817, 0.8884],
         [0.7346, 0.2910, 0.2024, 0.0456, 0.6751, 0.2020, 0.6584],
         [0.8044, 0.9796, 0.0070, 0.8486, 0.9713, 0.2311, 0.3601]]),
 torch.Size([7, 7]))

**2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)** (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
Y = torch.rand(size=(1, 7))
# Z = torch.matmul(X, Y) # will error because of shape issues
Z = torch.matmul(randtorch, Y.T) # no error because of transpose
Z, Z.shape

(tensor([[3.0454],
         [2.2614],
         [2.1790],
         [2.4411],
         [3.6862],
         [2.2787],
         [2.9945]]),
 torch.Size([7, 1]))

**3. Set the random seed to 0 and do 2 & 3 over again.**

The output should be:


```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))

```



In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

**4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?**

(hint: you'll need to look into the documentation for torch.cuda for this one)

If there is, set the GPU random seed to 1234.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

**5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:**

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


```



In [ ]:

# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

**6. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).**
The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```         

In [ ]:
# Perform matmul on tensor_A and tensor_B
# tensor_C = torch.matmul(tensor_A, tensor_B) # won't work because of shape error
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

**7. Find the maximum and minimum values of the output of 7.**

In [ ]:
# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

**8. Find the maximum and minimum index values of the output of 6.**

In [ ]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min


(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

**9. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.**

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```        

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


### Additional Exercise

In [ ]:
import torch
print(f"{torch.__version__}")

2.5.1+cu124
